Fix `AttributeError: 'ParallelExecutionStrategy' object has no attribute 'upper'`
I suspect pz is modifying the pz_config variable in-place internally, causing the 2nd invocation using the config to raise a type error